"""add llm error log

Revision ID: 6a166e7abe36
Revises: a4f21c9e8b73
Create Date: 2026-08-30 09:40:02.549196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a166e7abe36'
down_revision: Union[str, Sequence[str], None] = 'a4f21c9e8b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_llm_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WIDGET', 'KAKAO', name='llm_error_channel', native_enum=False, length=10), nullable=False),
    sa.Column('kind', sa.Enum('AUTH', 'QUOTA', 'TIMEOUT', 'OTHER', name='llm_error_kind', native_enum=False, length=10), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['tb_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_llm_errors_bot_id'), 'tb_llm_errors', ['bot_id'], unique=False)
    op.create_index(op.f('ix_tb_llm_errors_created_at'), 'tb_llm_errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_tb_llm_errors_id'), 'tb_llm_errors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_llm_errors_id'), table_name='tb_llm_errors')
    op.drop_index(op.f('ix_tb_llm_errors_created_at'), table_name='tb_llm_errors')
    op.drop_index(op.f('ix_tb_llm_errors_bot_id'), table_name='tb_llm_errors')
    op.drop_table('tb_llm_errors')
    # ### end Alembic commands ###
