"""update

Revision ID: 9515200216bc
Revises: 
Create Date: 2026-08-25 09:32:37.666462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9515200216bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_tb_admins_id'), 'tb_admins', ['id'], unique=False)
    op.create_table('tb_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('chat', 'image', name='model_type', native_enum=False, length=10), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'anthropic', 'gemini', name='model_provider', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('pricing_input', sa.Float(), nullable=True),
    sa.Column('pricing_output', sa.Float(), nullable=True),
    sa.Column('pricing_per_image', sa.Float(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_model_type_value')
    )
    op.create_index(op.f('ix_tb_models_id'), 'tb_models', ['id'], unique=False)
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('profile_image', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('workspace_name', sa.String(length=50), nullable=True),
    sa.Column('workspace_slug', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('workspace_slug')
    )
    op.create_index(op.f('ix_tb_users_id'), 'tb_users', ['id'], unique=False)
    op.create_table('tb_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'GOOGLE', name='api_key_provider', native_enum=False, length=20), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('last4', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_api_key_user_provider')
    )
    op.create_index(op.f('ix_tb_api_keys_id'), 'tb_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_tb_api_keys_user_id'), 'tb_api_keys', ['user_id'], unique=False)
    op.create_table('tb_bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('widget_icon', sa.Text(), nullable=True),
    sa.Column('greeting', sa.String(length=500), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('training_text', sa.Text(), nullable=True),
    sa.Column('training_type', sa.String(length=8), nullable=False),
    sa.Column('fallback', sa.String(length=500), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('vector_store_id', sa.String(length=64), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_bots_id'), 'tb_bots', ['id'], unique=False)
    op.create_index(op.f('ix_tb_bots_slug'), 'tb_bots', ['slug'], unique=True)
    op.create_index(op.f('ix_tb_bots_user_id'), 'tb_bots', ['user_id'], unique=False)
    op.create_table('tb_bot_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('openai_file_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['tb_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_bot_files_bot_id'), 'tb_bot_files', ['bot_id'], unique=False)
    op.create_index(op.f('ix_tb_bot_files_id'), 'tb_bot_files', ['id'], unique=False)
    op.create_index(op.f('ix_tb_bot_files_openai_file_id'), 'tb_bot_files', ['openai_file_id'], unique=False)
    op.create_table('tb_chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['tb_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_chat_sessions_bot_id'), 'tb_chat_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_tb_chat_sessions_id'), 'tb_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_tb_chat_sessions_visitor_id'), 'tb_chat_sessions', ['visitor_id'], unique=False)
    op.create_table('tb_chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'BOT', name='chat_message_role', native_enum=False, length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tb_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_chat_messages_id'), 'tb_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_tb_chat_messages_session_id'), 'tb_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_chat_messages_session_id'), table_name='tb_chat_messages')
    op.drop_index(op.f('ix_tb_chat_messages_id'), table_name='tb_chat_messages')
    op.drop_table('tb_chat_messages')
    op.drop_index(op.f('ix_tb_chat_sessions_visitor_id'), table_name='tb_chat_sessions')
    op.drop_index(op.f('ix_tb_chat_sessions_id'), table_name='tb_chat_sessions')
    op.drop_index(op.f('ix_tb_chat_sessions_bot_id'), table_name='tb_chat_sessions')
    op.drop_table('tb_chat_sessions')
    op.drop_index(op.f('ix_tb_bot_files_openai_file_id'), table_name='tb_bot_files')
    op.drop_index(op.f('ix_tb_bot_files_id'), table_name='tb_bot_files')
    op.drop_index(op.f('ix_tb_bot_files_bot_id'), table_name='tb_bot_files')
    op.drop_table('tb_bot_files')
    op.drop_index(op.f('ix_tb_bots_user_id'), table_name='tb_bots')
    op.drop_index(op.f('ix_tb_bots_slug'), table_name='tb_bots')
    op.drop_index(op.f('ix_tb_bots_id'), table_name='tb_bots')
    op.drop_table('tb_bots')
    op.drop_index(op.f('ix_tb_api_keys_user_id'), table_name='tb_api_keys')
    op.drop_index(op.f('ix_tb_api_keys_id'), table_name='tb_api_keys')
    op.drop_table('tb_api_keys')
    op.drop_index(op.f('ix_tb_users_id'), table_name='tb_users')
    op.drop_table('tb_users')
    op.drop_index(op.f('ix_tb_models_id'), table_name='tb_models')
    op.drop_table('tb_models')
    op.drop_index(op.f('ix_tb_admins_id'), table_name='tb_admins')
    op.drop_table('tb_admins')
    # ### end Alembic commands ###
